In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
%cd /content
!rm -rf PyHealth-TPC_LoS-AKV
!git clone https://github.com/Vismayak/PyHealth-TPC_LoS-AKV.git
%cd /content/PyHealth-TPC_LoS-AKV
!git checkout kchendv/Test
!git branch

/content
Cloning into 'PyHealth-TPC_LoS-AKV'...
remote: Enumerating objects: 9790, done.
remote: Counting objects: 100% (549/549), done.
remote: Compressing objects: 100% (127/127), done.
remote: Total 9790 (delta 472), reused 424 (delta 422), pack-reused 9241 (from 1)
Receiving objects: 100% (9790/9790), 131.74 MiB | 1.00 MiB/s, done.
Resolving deltas: 100% (6202/6202), done.
/content/PyHealth-TPC_LoS-AKV
Branch 'kchendv/Test' set up to track remote branch 'kchendv/Test' from 'origin'.
Switched to a new branch 'kchendv/Test'
* kchendv/Test
  master

In [ ]:
%cd /content/PyHealth-TPC_LoS-AKV
!pip install litdata
!pip install -e .

/content/PyHealth-TPC_LoS-AKV
Requirement already satisfied: litdata in /usr/local/lib/python3.12/dist-packages (0.2.61)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from litdata) (2.7.1)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from litdata) (0.22.1)
Requirement already satisfied: lightning-utilities in /usr/local/lib/python3.12/dist-packages (from litdata) (0.15.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from litdata) (3.25.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from litdata) (2.2.6)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from litdata) (1.42.89)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from litdata) (2.32.4)
Requirement already satisfied: tifffile in /usr/local/lib/python3.12/dist-packages (from litdata) (2026.3.3)
Requirement already satisfied: obstore in /usr/local/lib/python3.12/dist-packages (from litdata) (0.9.3)
Requirement already satisfied: botocore<1.43.0,>=1.42.89 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata) (1.42.89)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata) (0.16.0)
Requirement already satisfied: packaging>=22 in /usr/local/lib/python3.12/dist-packages (from lightning-utilities->litdata) (26.0)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.12/dist-packages (from lightning-utilities->litdata) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->litdata) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->litdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->litdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->litdata) (2026.2.25)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (1.14.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /usr/local/lib/python3.12/dist-packages (from torch->litdata) (3.3.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision->litdata) (11.3.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.12/dist-packages (from botocore<1.43.0,>=1.42.89->boto3->litdata) (2.9.0.post0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->litdata) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->litdata) (3.0.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.89->boto3->litdata) (1.17.0)
Obtaining file:///content/PyHealth-TPC_LoS-AKV
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.13.0)
Requirement already satisfied: dask~=2025.11.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]~=2025.11.0->pyhealth==2.0.0) (2025.11.0)
Requirement already satisfied: einops>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.8.2)
Requirement already satisfied: linear-attention-transformer>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.19.1)
Requirement already satisfied: litdata~=0.2.59 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.2.61)
Requirement already satisfied: mne~=1.10.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.10.2)
Requirement already satisfied: more-itertools~=10.8.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (10.8.0)
Requirement already satisfied: narwhals~=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (3.6.1)
Requirement already satisfied: numpy~=2.2.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.2.6)
Requirement already satisfied: ogb>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.3.6)
Requirement already satisfied: pandas~=2.3.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.3.3)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.18.1)
Requirement already satisfied: polars~=1.35.2 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.35.2)
Requirement already satisfied: pyarrow~=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (22.0.0)
Requirement already satisfied: pydantic~=2.11.7 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.11.10)
Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2026.3.1)
Requirement already satisfied: scikit-learn~=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.7.2)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.22.1)
Requirement already satisfied: torch~=2.7.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.7.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (4.67.3)
Requirement already satisfied: transformers~=4.53.2 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (4.53.3)
Requirement already satisfied: urllib3~=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.5.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (8.3.2)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (0.12.1)
Requirement already satisfied: lz4>=4.3.2 in /usr/local/lib/python3.12/dist-packages (from dask[complete]~=2025.11.0->pyhealth==2.0.0) (4.4.5)
Requirement already satisfied: axial-positional-embedding in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.3.12)
Requirement already satisfied: linformer>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.2.3)
Requirement already satisfied: local-attention in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (1.11.2)
Requirement already satisfied: product-key-memory>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.3.0)
Requirement already satisfied: lightning-utilities in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (0.15.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (3.25.2)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (1.42.89)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (2.32.4)
Requirement already satisfied: tifffile in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (2026.3.3)
Requirement already satisfied: obstore in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (0.9.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (4.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (3.1.6)
Requirement already satisfied: lazy-loader>=0.3 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (0.5)
Requirement already satisfied: matplotlib>=3.7 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (3.10.0)
Requirement already satisfied: pooch>=1.5 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (1.9.0)
Requirement already satisfied: scipy>=1.11 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (1.16.3)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ogb>=1.3.5->pyhealth==2.0.0) (1.17.0)
Requirement already satisfied: outdated>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ogb>=1.3.5->pyhealth==2.0.0) (0.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2026.1)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars~=1.35.2->pyhealth==2.0.0) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (0.4.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn~=1.7.0->pyhealth==2.0.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn~=1.7.0->pyhealth==2.0.0) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (1.14.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (3.3.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.36.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (2025.11.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->pyhealth==2.0.0) (5.9.5)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from rdkit->pyhealth==2.0.0) (11.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers~=4.53.2->pyhealth==2.0.0) (1.4.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (3.3.2)
Requirement already satisfied: littleutils in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb>=1.3.5->pyhealth==2.0.0) (0.2.4)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (1.0.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.5->mne~=1.10.0->pyhealth==2.0.0) (4.9.6)
Requirement already satisfied: colt5-attention>=0.10.14 in /usr/local/lib/python3.12/dist-packages (from product-key-memory>=0.1.5->linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.11.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch~=2.7.1->pyhealth==2.0.0) (1.3.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.89 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (1.42.89)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (0.16.0)

In [ ]:
%cd /content/PyHealth-TPC_LoS-AKV
!pip install --upgrade pip
!pip install -e .
!pip install scikit-learn pandas

/content/PyHealth-TPC_LoS-AKV
Requirement already satisfied: pip in /usr/local/lib/python3.12/dist-packages (24.1.2)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 24.1.2
    Uninstalling pip-24.1.2:
      Successfully uninstalled pip-24.1.2
Successfully installed pip-26.0.1
Obtaining file:///content/PyHealth-TPC_LoS-AKV
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.13.0)
Requirement already satisfied: dask~=2025.11.0 in /usr/local/lib/python3.12/dist-packages (from dask[complete]~=2025.11.0->pyhealth==2.0.0) (2025.11.0)
Requirement already satisfied: einops>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.8.2)
Requirement already satisfied: linear-attention-transformer>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.19.1)
Requirement already satisfied: litdata~=0.2.59 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.2.61)
Requirement already satisfied: mne~=1.10.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.10.2)
Requirement already satisfied: more-itertools~=10.8.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (10.8.0)
Requirement already satisfied: narwhals~=2.13.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.13.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (3.6.1)
Requirement already satisfied: numpy~=2.2.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.2.6)
Requirement already satisfied: ogb>=1.3.5 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.3.6)
Requirement already satisfied: pandas~=2.3.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.3.3)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.18.1)
Requirement already satisfied: polars~=1.35.2 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.35.2)
Requirement already satisfied: pyarrow~=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (22.0.0)
Requirement already satisfied: pydantic~=2.11.7 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.11.10)
Requirement already satisfied: rdkit in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2026.3.1)
Requirement already satisfied: scikit-learn~=1.7.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (1.7.2)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (0.22.1)
Requirement already satisfied: torch~=2.7.1 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.7.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (4.67.3)
Requirement already satisfied: transformers~=4.53.2 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (4.53.3)
Requirement already satisfied: urllib3~=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pyhealth==2.0.0) (2.5.0)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (8.3.2)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (6.0.3)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (0.12.1)
Requirement already satisfied: lz4>=4.3.2 in /usr/local/lib/python3.12/dist-packages (from dask[complete]~=2025.11.0->pyhealth==2.0.0) (4.4.5)
Requirement already satisfied: lightning-utilities in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (0.15.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (3.25.2)
Requirement already satisfied: boto3 in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (1.42.89)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (2.32.4)
Requirement already satisfied: tifffile in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (2026.3.3)
Requirement already satisfied: obstore in /usr/local/lib/python3.12/dist-packages (from litdata~=0.2.59->pyhealth==2.0.0) (0.9.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (4.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (3.1.6)
Requirement already satisfied: lazy-loader>=0.3 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (0.5)
Requirement already satisfied: matplotlib>=3.7 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (3.10.0)
Requirement already satisfied: pooch>=1.5 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (1.9.0)
Requirement already satisfied: scipy>=1.11 in /usr/local/lib/python3.12/dist-packages (from mne~=1.10.0->pyhealth==2.0.0) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas~=2.3.1->pyhealth==2.0.0) (2026.1)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars~=1.35.2->pyhealth==2.0.0) (1.35.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic~=2.11.7->pyhealth==2.0.0) (0.4.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn~=1.7.0->pyhealth==2.0.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn~=1.7.0->pyhealth==2.0.0) (3.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (1.14.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.5.1.17 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (9.5.1.17)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.3 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (0.6.3)
Requirement already satisfied: nvidia-nccl-cu12==2.26.2 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (2.26.2)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (1.11.1.6)
Requirement already satisfied: triton==3.3.1 in /usr/local/lib/python3.12/dist-packages (from torch~=2.7.1->pyhealth==2.0.0) (3.3.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.36.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (2025.11.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers~=4.53.2->pyhealth==2.0.0) (0.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers~=4.53.2->pyhealth==2.0.0) (1.4.3)
Requirement already satisfied: axial-positional-embedding in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.3.12)
Requirement already satisfied: linformer>=0.1.0 in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.2.3)
Requirement already satisfied: local-attention in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (1.11.2)
Requirement already satisfied: product-key-memory>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.3.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.7->mne~=1.10.0->pyhealth==2.0.0) (3.3.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ogb>=1.3.5->pyhealth==2.0.0) (1.17.0)
Requirement already satisfied: outdated>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ogb>=1.3.5->pyhealth==2.0.0) (0.2.2)
Requirement already satisfied: littleutils in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb>=1.3.5->pyhealth==2.0.0) (0.2.4)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (1.0.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.5->mne~=1.10.0->pyhealth==2.0.0) (4.9.6)
Requirement already satisfied: colt5-attention>=0.10.14 in /usr/local/lib/python3.12/dist-packages (from product-key-memory>=0.1.5->linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.11.1)
Requirement already satisfied: hyper-connections>=0.1.8 in /usr/local/lib/python3.12/dist-packages (from local-attention->linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.4.9)
Requirement already satisfied: torch-einops-utils>=0.0.20 in /usr/local/lib/python3.12/dist-packages (from hyper-connections>=0.1.8->local-attention->linear-attention-transformer>=0.19.1->pyhealth==2.0.0) (0.0.30)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->litdata~=0.2.59->pyhealth==2.0.0) (2026.2.25)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch~=2.7.1->pyhealth==2.0.0) (1.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate->pyhealth==2.0.0) (5.9.5)
Requirement already satisfied: botocore<1.43.0,>=1.42.89 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (1.42.89)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /usr/local/lib/python3.12/dist-packages (from boto3->litdata~=0.2.59->pyhealth==2.0.0) (0.16.0)
Requirement already satisfied: distributed==2025.11.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (2025.11.0)
Requirement already satisfied: bokeh>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (3.8.2)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.11.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (1.1.2)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.11.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.11.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (3.2.2)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.11.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (6.5.1)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from distributed==2025.11.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (3.0.0)
Requirement already satisfied: xyzservices>=2021.09.1 in /usr/local/lib/python3.12/dist-packages (from bokeh>=3.1.0->dask~=2025.11.0->dask[complete]~=2025.11.0->pyhealth==2.0.0) (2026.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->mne~=1.10.0->pyhealth==2.0.0) (3.0.3)
Building wheels for collected packages: pyhealth
  Building editable for pyhealth (pyproject.toml) ... done
  Created wheel for pyhealth: filename=pyhealth-2.0.0-py3-none-any.whl size=10689 sha256=66c0cefb8783b90c798dad827a552f83c51bba1d5b21cf57b8c75434855356d6
  Stored in directory: /tmp/pip-ephem-wheel-cache-c9plpufa/wheels/1d/16/c5/0ce41b017ae1bd5236c56bc2fbeec31ce2bceaf3d6e7eab939
Successfully built pyhealth
Installing collected packages: pyhealth
  Attempting uninstall: pyhealth
    Found existing installation: pyhealth 2.0.0
    Uninstalling pyhealth-2.0.0:
      Successfully uninstalled pyhealth-2.0.0
Successfully installed pyhealth-2.0.0
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.7.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: numpy>=1.22.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!ls pyhealth/models | head
!ls pyhealth/tasks | head -30
!ls examples

adacare.py
agent.py
base_model.py
biot.py
cnn.py
concare.py
contrawr.py
deepr.py
ehrmamba.py
embedding.py
base_task.py
benchmark_ehrshot.py
bmd_hs_disease_classification.py
cancer_survival.py
cardiology_detect.py
chestxray14_binary_classification.py
chestxray14_multilabel_classification.py
covid19_cxr_classification.py
dka.py
drug_recommendation.py
in_hospital_mortality_mimic4.py
__init__.py
length_of_stay_prediction.py
length_of_stay_stagenet_mimic4.py
medical_coding.py
medical_transcriptions_classification.py
mortality_prediction.py
mortality_prediction_stagenet_mimic4.py
patient_linkage_mimic3.py
patient_linkage.py
readmission_prediction.py
remaining_length_of_stay_tpc_mimic4.py
sleep_staging.py
sleep_staging_v2.py
survival_preprocess_support2.py
temple_university_EEG_tasks.py
variant_classification.py
agent_mimic4.ipynb
benchmark_ehrshot_xgboost.ipynb
benchmark_perf
benchmark_pyhealth.ipynb
cardiology_detection_isAR_SparcNet.py
clinical_tasks
cnn_mimic4.ipynb
concare_mimic4_example.ipynb
conformal_eeg
cxr
datasets_overview.ipynb
deepr_mimic4.ipynb
drug_recommendation
eeg
ehrmamba_mimic4.ipynb
gamenet_mimic3.ipynb
gat_mimic4.ipynb
gcn_mimic4.ipynb
graphcare_tutorial.ipynb
graph_torchvision_model.ipynb
interpretability
kg_embedding.ipynb
length_of_stay
lime_stagenet_mimic4.py
lm_embedding_huggingface.ipynb
lm_embedding_openai.ipynb
medcode.py
medical_coding_mimic3.ipynb
medlink_mimic3.ipynb
memtest.py
molerec_mimic3.ipynb
mortality_prediction
omop_dataset_demo.py
patient_linkage_mimic3_medlink.py
prepare_mapping.ipynb
readmission
run_tpc_mimic4_full.py
smart_processor_clinical_text_tutorial.ipynb
sparcnet_sleepedf.ipynb
survival_preprocess_support2_demo.py
tcn_mimic3_codes.ipynb
test.py
text_embedding_tutorial.ipynb
time_image_processor_tutorial.ipynb
tpc_mimic4_full_mimic_train.ipynb
tpc_mimic4_remaining_los_debug.ipynb
tpc_mimic4_remaining_los.py
transformer_mimic4.ipynb
tutorial_stagenet_comprehensive.ipynb
vision_embedding_tutorial.ipynb

In [ ]:
DATA_ROOT = "/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2"
print(DATA_ROOT)

/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2

In [ ]:
import os

required_files = [
    ("hosp", "patients.csv.gz"),
    ("hosp", "admissions.csv.gz"),
    ("icu", "icustays.csv.gz"),
    ("hosp", "labevents.csv.gz"),
    ("hosp", "d_labitems.csv.gz"),
    ("icu", "chartevents.csv.gz"),
]

print("Checking required files...\n")
all_ok = True

for sub, fn in required_files:
    path = os.path.join(DATA_ROOT, sub, fn)
    exists = os.path.exists(path)
    print(f"{path}: {exists}")
    if not exists:
        all_ok = False

print("\nAll files found:", all_ok)

Checking required files...

/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz: True
/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz: True
/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz: True
/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz: True
/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz: True
/content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz: True

All files found: True

In [ ]:
import os
import sys
import numpy as np
import pandas as pd
from typing import List

REPO_ROOT = "/content/PyHealth-TPC_LoS-AKV"
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

os.environ["PYHEALTH_CACHE_PATH"] = os.path.join(REPO_ROOT, ".pyhealth_cache")

from pyhealth.datasets import MIMIC4EHRDataset, get_dataloader, split_by_patient
from pyhealth.models import TPC
from pyhealth.tasks import RemainingLengthOfStayTPC_MIMIC4
from pyhealth.tasks.length_of_stay_prediction import categorize_los
from pyhealth.trainer import Trainer

/content/PyHealth-TPC_LoS-AKV/pyhealth/metrics/calibration.py:122: SyntaxWarning: invalid escape sequence '\c'
  accuracy of 1. Thus, the ECE is :math:`\\frac{1}{3} \cdot 0.49 + \\frac{2}{3}\cdot 0.3=0.3633`.

In [ ]:
def bin_remaining_los_days(y_days: np.ndarray) -> np.ndarray:
    flat = y_days.reshape(-1)
    out = np.zeros_like(flat, dtype=int)
    for i, value in enumerate(flat):
        if value == 0:
            out[i] = -1
        else:
            out[i] = categorize_los(int(np.floor(value)))
    return out.reshape(y_days.shape)


def masked_kappa_and_accuracy(y_true_days: np.ndarray, y_pred_days: np.ndarray):
    from sklearn.metrics import cohen_kappa_score

    y_true_bin = bin_remaining_los_days(y_true_days)
    y_pred_bin = bin_remaining_los_days(y_pred_days)

    mask = y_true_bin != -1
    yt = y_true_bin[mask]
    yp = y_pred_bin[mask]

    acc = float((yt == yp).mean()) if yt.size else float("nan")
    kappa = float(cohen_kappa_score(yt, yp)) if yt.size else float("nan")
    return kappa, acc

In [ ]:
import torch
import torch.nn.functional as F
import numpy as np


def safe_variable_length_inference(model, dataloader, device=None):
    """
    Runs inference batch-by-batch and pads variable-length predictions/labels
    so they can be concatenated safely across batches.
    """
    if device is None:
        device = next(model.parameters()).device

    model.eval()

    y_true_all = []
    y_pred_all = []
    loss_all = []

    max_len = 0

    with torch.no_grad():
        for data in dataloader:
            # move tensors to device when possible
            batch = {}
            for k, v in data.items():
                if isinstance(v, torch.Tensor):
                    batch[k] = v.to(device)
                else:
                    batch[k] = v

            output = model(**batch)

            # expected keys from PyHealth model output
            y_true = output["y_true"].detach().cpu().numpy()
            y_pred = output["y_prob"].detach().cpu().numpy()
            loss = output["loss"].item()

            y_true_all.append(y_true)
            y_pred_all.append(y_pred)
            loss_all.append(loss)

            max_len = max(max_len, y_true.shape[1])

    # pad each batch to max_len along time dimension
    padded_true = []
    padded_pred = []

    for yt, yp in zip(y_true_all, y_pred_all):
        pad_width = max_len - yt.shape[1]

        if pad_width > 0:
            yt = np.pad(yt, ((0, 0), (0, pad_width)), mode="constant", constant_values=0)
            yp = np.pad(yp, ((0, 0), (0, pad_width)), mode="constant", constant_values=0)

        padded_true.append(yt)
        padded_pred.append(yp)

    y_true_concat = np.concatenate(padded_true, axis=0)
    y_pred_concat = np.concatenate(padded_pred, axis=0)
    loss_mean = float(np.mean(loss_all))

    return y_true_concat, y_pred_concat, loss_mean

In [ ]:
# Kevin's current minimal lab feature set
labevent_itemids = [
    "50824", "52455", "50983", "52623", "50822", "52452", "50971",
    "52610", "50806", "52434", "50902", "52535", "50803", "50804",
    "50809", "52027", "50931", "52569", "50808", "51624", "50960",
    "50868", "52500", "52031", "50964", "51701", "50970",
]

# Common MIMIC-IV chartevent vital signs
chart_vitals_itemids = [
    "220045",  # heart rate
    "220179",  # systolic BP
    "220180",  # diastolic BP
    "220181",  # mean BP
    "220210",  # respiratory rate
    "224690",  # respiratory rate total
    "223761",  # temperature F
    "223762",  # temperature C
    "220277",  # SpO2
    "225664",  # glucose fingerstick
    "220621",  # glucose serum
    "226537",  # glucose whole blood
]

In [ ]:
dataset = MIMIC4EHRDataset(
    root=DATA_ROOT,
    tables=["patients", "admissions", "icustays", "labevents", "chartevents"],
    dev=True,
    num_workers=2,
    cache_dir=os.path.join(REPO_ROOT, ".sanity_cache"),
)

print(dataset)

Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

INFO:pyhealth.datasets.mimic4:Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

Memory usage Before initializing mimic4_ehr: 3981.6 MB

INFO:pyhealth.datasets.mimic4:Memory usage Before initializing mimic4_ehr: 3981.6 MB

Duplicate table names in tables list. Removing duplicates.

WARNING:pyhealth.datasets.base_dataset:Duplicate table names in tables list. Removing duplicates.

Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: True)

INFO:pyhealth.datasets.base_dataset:Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: True)

Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f

INFO:pyhealth.datasets.base_dataset:Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f

Memory usage After initializing mimic4_ehr: 3981.6 MB

INFO:pyhealth.datasets.mimic4:Memory usage After initializing mimic4_ehr: 3981.6 MB

<pyhealth.datasets.mimic4.MIMIC4EHRDataset object at 0x79daae584290>

In [ ]:

task = RemainingLengthOfStayTPC_MIMIC4(
    labevent_itemids=labevent_itemids,
    chartevent_itemids=[],
)

sample_dataset = dataset.set_task(task)
print(sample_dataset)
print("Number of samples:", len(sample_dataset))

Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

INFO:pyhealth.datasets.base_dataset:Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Found cached processed samples at /content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld, skipping processing.

INFO:pyhealth.datasets.base_dataset:Found cached processed samples at /content/PyHealth-TPC_LoS-AKV/.sanity_cache/bd083a71-5694-5c04-bc43-a68a618f615f/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld, skipping processing.

Sample dataset mimic4_ehr RemainingLengthOfStayTPC_MIMIC4
Number of samples: 23

In [ ]:
def run_experiment(
    name: str,
    root: str,
    cache_dir: str,
    labevent_itemids: List[str],
    chartevent_itemids: List[str],
    epochs: int = 1,
):
    print(f"\n========== Running experiment: {name} ==========")
    print(f"Lab features: {len(labevent_itemids)}")
    print(f"Chart features: {len(chartevent_itemids)}")

    dataset = MIMIC4EHRDataset(
        root=root,
        tables=["patients", "admissions", "icustays", "labevents", "chartevents"],
        dev=False,
        num_workers=2,
        cache_dir=cache_dir,
    )

    task = RemainingLengthOfStayTPC_MIMIC4(
        labevent_itemids=labevent_itemids,
        chartevent_itemids=chartevent_itemids,
    )

    sample_dataset = dataset.set_task(task)
    print("Task dataset built. Number of samples:", len(sample_dataset))

    train_ds, val_ds, test_ds = split_by_patient(sample_dataset, ratios=[0.8, 0.1, 0.1])

    print("Train:", len(train_ds))
    print("Val:", len(val_ds))
    print("Test:", len(test_ds))

    train_loader = get_dataloader(train_ds, batch_size=8, shuffle=True)
    val_loader = get_dataloader(val_ds, batch_size=8, shuffle=False)
    test_loader = get_dataloader(test_ds, batch_size=8, shuffle=False)

    model = TPC(
        dataset=sample_dataset,
        temporal_channels=11,
        pointwise_channels=5,
        num_layers=8,
        kernel_size=5,
        main_dropout=0.0,
        temporal_dropout=0.05,
        use_batchnorm=True,
        final_hidden=36,
    )

    trainer = Trainer(
        model=model,
        metrics=["mae", "mse"],
        enable_logging=False,
    )

    trainer.train(
        train_dataloader=train_loader,
        val_dataloader=None,
        test_dataloader=None,
        epochs=epochs,
        monitor="mae",
        monitor_criterion="min",
        optimizer_params={"lr": 0.00221},
    )

    # use safe inference instead of trainer.inference(...)
    y_true, y_pred, _ = safe_variable_length_inference(model, test_loader)

    kappa, acc = masked_kappa_and_accuracy(y_true, y_pred)
    mae = float(np.mean(np.abs(y_true - y_pred)))
    mse = float(np.mean((y_true - y_pred) ** 2))

    result = {
        "experiment": name,
        "mae": mae,
        "mse": mse,
        "kappa": kappa,
        "accuracy": acc,
    }

    print("Result:", result)
    return result

In [ ]:
baseline_result = run_experiment(
    name="lab_only_debug",
    root=DATA_ROOT,
    cache_dir=os.path.join(REPO_ROOT, ".ablation_cache", "lab_only_debug"),
    labevent_itemids=labevent_itemids,
    chartevent_itemids=[],
    epochs=1,
)

baseline_result

========== Running experiment: lab_only_debug ==========
Lab features: 27
Chart features: 0
Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

INFO:pyhealth.datasets.mimic4:Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

Memory usage Before initializing mimic4_ehr: 4252.0 MB

INFO:pyhealth.datasets.mimic4:Memory usage Before initializing mimic4_ehr: 4252.0 MB

Duplicate table names in tables list. Removing duplicates.

WARNING:pyhealth.datasets.base_dataset:Duplicate table names in tables list. Removing duplicates.

Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

INFO:pyhealth.datasets.base_dataset:Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4

INFO:pyhealth.datasets.base_dataset:Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4

Memory usage After initializing mimic4_ehr: 4252.0 MB

INFO:pyhealth.datasets.mimic4:Memory usage After initializing mimic4_ehr: 4252.0 MB

Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

INFO:pyhealth.datasets.base_dataset:Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Found cached processed samples at /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld, skipping processing.

INFO:pyhealth.datasets.base_dataset:Found cached processed samples at /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only_debug/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld, skipping processing.

Task dataset built. Number of samples: 137
Train: 113
Val: 12
Test: 12
TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(54, 297, kernel_size=(5,), stride=(1,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(2,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(3,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(4,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(5,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(624, 572, kernel_size=(5,), stride=(1,), dilation=(6,), groups=52)
      (bn_temporal): BatchNorm1d(572, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=672, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(684, 627, kernel_size=(5,), stride=(1,), dilation=(7,), groups=57)
      (bn_temporal): BatchNorm1d(627, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=732, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(744, 682, kernel_size=(5,), stride=(1,), dilation=(8,), groups=62)
      (bn_temporal): BatchNorm1d(682, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=792, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=852, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

INFO:pyhealth.trainer:TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(54, 297, kernel_size=(5,), stride=(1,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(2,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(3,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(4,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(5,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(624, 572, kernel_size=(5,), stride=(1,), dilation=(6,), groups=52)
      (bn_temporal): BatchNorm1d(572, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=672, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(684, 627, kernel_size=(5,), stride=(1,), dilation=(7,), groups=57)
      (bn_temporal): BatchNorm1d(627, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=732, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(744, 682, kernel_size=(5,), stride=(1,), dilation=(8,), groups=62)
      (bn_temporal): BatchNorm1d(682, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=792, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=852, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

Metrics: ['mae', 'mse']

INFO:pyhealth.trainer:Metrics: ['mae', 'mse']

Device: cpu

INFO:pyhealth.trainer:Device: cpu

INFO:pyhealth.trainer:

Training:

INFO:pyhealth.trainer:Training:

Batch size: 8

INFO:pyhealth.trainer:Batch size: 8

Optimizer: <class 'torch.optim.adam.Adam'>

INFO:pyhealth.trainer:Optimizer: <class 'torch.optim.adam.Adam'>

Optimizer params: {'lr': 0.00221}

INFO:pyhealth.trainer:Optimizer params: {'lr': 0.00221}

Weight decay: 0.0

INFO:pyhealth.trainer:Weight decay: 0.0

Max grad norm: None

INFO:pyhealth.trainer:Max grad norm: None

Val dataloader: None

INFO:pyhealth.trainer:Val dataloader: None

Monitor: mae

INFO:pyhealth.trainer:Monitor: mae

Monitor criterion: min

INFO:pyhealth.trainer:Monitor criterion: min

Epochs: 1

INFO:pyhealth.trainer:Epochs: 1

Patience: None

INFO:pyhealth.trainer:Patience: None

INFO:pyhealth.trainer:

Epoch 0 / 1:   0%|          | 0/15 [00:00<?, ?it/s]

--- Train epoch-0, step-15 ---

INFO:pyhealth.trainer:--- Train epoch-0, step-15 ---

loss: 1.6601

INFO:pyhealth.trainer:loss: 1.6601

Result: {'experiment': 'lab_only_debug', 'mae': 1.3433852195739746, 'mse': 5.318716526031494, 'kappa': -0.03867319195214791, 'accuracy': 0.19047619047619047}

{'experiment': 'lab_only_debug',
 'mae': 1.3433852195739746,
 'mse': 5.318716526031494,
 'kappa': -0.03867319195214791,
 'accuracy': 0.19047619047619047}

In [ ]:
experiments = [
    {
        "name": "lab_only",
        "labevent_itemids": labevent_itemids,
        "chartevent_itemids": [],
    },
    {
        "name": "chart_only",
        "labevent_itemids": [],
        "chartevent_itemids": chart_vitals_itemids,
    },
    {
        "name": "lab_plus_chart",
        "labevent_itemids": labevent_itemids,
        "chartevent_itemids": chart_vitals_itemids,
    },
]

experiments

[{'name': 'lab_only',
  'labevent_itemids': ['50824',
   '52455',
   '50983',
   '52623',
   '50822',
   '52452',
   '50971',
   '52610',
   '50806',
   '52434',
   '50902',
   '52535',
   '50803',
   '50804',
   '50809',
   '52027',
   '50931',
   '52569',
   '50808',
   '51624',
   '50960',
   '50868',
   '52500',
   '52031',
   '50964',
   '51701',
   '50970'],
  'chartevent_itemids': []},
 {'name': 'chart_only',
  'labevent_itemids': [],
  'chartevent_itemids': ['220045',
   '220179',
   '220180',
   '220181',
   '220210',
   '224690',
   '223761',
   '223762',
   '220277',
   '225664',
   '220621',
   '226537']},
 {'name': 'lab_plus_chart',
  'labevent_itemids': ['50824',
   '52455',
   '50983',
   '52623',
   '50822',
   '52452',
   '50971',
   '52610',
   '50806',
   '52434',
   '50902',
   '52535',
   '50803',
   '50804',
   '50809',
   '52027',
   '50931',
   '52569',
   '50808',
   '51624',
   '50960',
   '50868',
   '52500',
   '52031',
   '50964',
   '51701',
   '50970'],
  'chartevent_itemids': ['220045',
   '220179',
   '220180',
   '220181',
   '220210',
   '224690',
   '223761',
   '223762',
   '220277',
   '225664',
   '220621',
   '226537']}]

In [ ]:
all_results = []

for exp in experiments:
    result = run_experiment(
        name=exp["name"],
        root=DATA_ROOT,
        cache_dir=os.path.join(REPO_ROOT, ".ablation_cache", exp["name"]),
        labevent_itemids=exp["labevent_itemids"],
        chartevent_itemids=exp["chartevent_itemids"],
        epochs=1,
    )
    all_results.append(result)

========== Running experiment: lab_only ==========
Lab features: 27
Chart features: 0
Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

INFO:pyhealth.datasets.mimic4:Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

Memory usage Before initializing mimic4_ehr: 4285.9 MB

INFO:pyhealth.datasets.mimic4:Memory usage Before initializing mimic4_ehr: 4285.9 MB

Duplicate table names in tables list. Removing duplicates.

WARNING:pyhealth.datasets.base_dataset:Duplicate table names in tables list. Removing duplicates.

Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

INFO:pyhealth.datasets.base_dataset:Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4

INFO:pyhealth.datasets.base_dataset:Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4

Memory usage After initializing mimic4_ehr: 4285.9 MB

INFO:pyhealth.datasets.mimic4:Memory usage After initializing mimic4_ehr: 4285.9 MB

Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

INFO:pyhealth.datasets.base_dataset:Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Applying task transformations on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying task transformations on data with 2 workers...

No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

INFO:pyhealth.datasets.base_dataset:No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

INFO:pyhealth.datasets.base_dataset:Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

INFO:pyhealth.datasets.base_dataset:Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 100 patients. (Polars threads: 2)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 100 patients. (Polars threads: 2)
  0%|          | 0/100 [00:00<?, ?it/s]

Rank 0 inferred the following `['bytes']` data format.

100%|██████████| 100/100 [00:04<00:00, 21.18it/s]

Worker 0 finished processing patients.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing patients.

Fitting processors on the dataset...

INFO:pyhealth.datasets.base_dataset:Fitting processors on the dataset...

Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

INFO:pyhealth.datasets.base_dataset:Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

Applying processors on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying processors on data with 2 workers...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 137 samples. (0 to 137)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 137 samples. (0 to 137)
  0%|          | 0/137 [00:00<?, ?it/s]

Rank 0 inferred the following `['str', 'str', 'str', 'no_header_tensor:1', 'tensor', 'no_header_tensor:1']` data format.

100%|██████████| 137/137 [00:00<00:00, 349.42it/s]

Worker 0 finished processing samples.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing samples.

Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_80fb1568-627f-54f4-96a9-bec1fde5997e/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Task dataset built. Number of samples: 137
Train: 112
Val: 12
Test: 13
TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(54, 297, kernel_size=(5,), stride=(1,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(2,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(3,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(4,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(5,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(624, 572, kernel_size=(5,), stride=(1,), dilation=(6,), groups=52)
      (bn_temporal): BatchNorm1d(572, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=672, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(684, 627, kernel_size=(5,), stride=(1,), dilation=(7,), groups=57)
      (bn_temporal): BatchNorm1d(627, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=732, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(744, 682, kernel_size=(5,), stride=(1,), dilation=(8,), groups=62)
      (bn_temporal): BatchNorm1d(682, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=792, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=852, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

INFO:pyhealth.trainer:TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(54, 297, kernel_size=(5,), stride=(1,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(2,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(3,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(4,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(5,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(624, 572, kernel_size=(5,), stride=(1,), dilation=(6,), groups=52)
      (bn_temporal): BatchNorm1d(572, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=672, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(684, 627, kernel_size=(5,), stride=(1,), dilation=(7,), groups=57)
      (bn_temporal): BatchNorm1d(627, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=732, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(744, 682, kernel_size=(5,), stride=(1,), dilation=(8,), groups=62)
      (bn_temporal): BatchNorm1d(682, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=792, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=852, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

Metrics: ['mae', 'mse']

INFO:pyhealth.trainer:Metrics: ['mae', 'mse']

Device: cpu

INFO:pyhealth.trainer:Device: cpu

INFO:pyhealth.trainer:

Training:

INFO:pyhealth.trainer:Training:

Batch size: 8

INFO:pyhealth.trainer:Batch size: 8

Optimizer: <class 'torch.optim.adam.Adam'>

INFO:pyhealth.trainer:Optimizer: <class 'torch.optim.adam.Adam'>

Optimizer params: {'lr': 0.00221}

INFO:pyhealth.trainer:Optimizer params: {'lr': 0.00221}

Weight decay: 0.0

INFO:pyhealth.trainer:Weight decay: 0.0

Max grad norm: None

INFO:pyhealth.trainer:Max grad norm: None

Val dataloader: None

INFO:pyhealth.trainer:Val dataloader: None

Monitor: mae

INFO:pyhealth.trainer:Monitor: mae

Monitor criterion: min

INFO:pyhealth.trainer:Monitor criterion: min

Epochs: 1

INFO:pyhealth.trainer:Epochs: 1

Patience: None

INFO:pyhealth.trainer:Patience: None

INFO:pyhealth.trainer:

Epoch 0 / 1:   0%|          | 0/14 [00:00<?, ?it/s]

--- Train epoch-0, step-14 ---

INFO:pyhealth.trainer:--- Train epoch-0, step-14 ---

loss: 1.7247

INFO:pyhealth.trainer:loss: 1.7247

Result: {'experiment': 'lab_only', 'mae': 1.8505560159683228, 'mse': 10.661467552185059, 'kappa': 0.006731923973546938, 'accuracy': 0.18916595012897677}

========== Running experiment: chart_only ==========
Lab features: 0
Chart features: 12
Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

INFO:pyhealth.datasets.mimic4:Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

Memory usage Before initializing mimic4_ehr: 4758.5 MB

INFO:pyhealth.datasets.mimic4:Memory usage Before initializing mimic4_ehr: 4758.5 MB

Duplicate table names in tables list. Removing duplicates.

WARNING:pyhealth.datasets.base_dataset:Duplicate table names in tables list. Removing duplicates.

Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

INFO:pyhealth.datasets.base_dataset:Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4

INFO:pyhealth.datasets.base_dataset:Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4

Memory usage After initializing mimic4_ehr: 4758.5 MB

INFO:pyhealth.datasets.mimic4:Memory usage After initializing mimic4_ehr: 4758.5 MB

Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

INFO:pyhealth.datasets.base_dataset:Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Applying task transformations on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying task transformations on data with 2 workers...

No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

INFO:pyhealth.datasets.base_dataset:No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

INFO:pyhealth.datasets.base_dataset:Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

INFO:pyhealth.datasets.base_dataset:Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 100 patients. (Polars threads: 2)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 100 patients. (Polars threads: 2)
  0%|          | 0/100 [00:00<?, ?it/s]

Rank 0 inferred the following `['bytes']` data format.

100%|██████████| 100/100 [00:02<00:00, 38.72it/s]

Worker 0 finished processing patients.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing patients.

Fitting processors on the dataset...

INFO:pyhealth.datasets.base_dataset:Fitting processors on the dataset...

Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

INFO:pyhealth.datasets.base_dataset:Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

Applying processors on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying processors on data with 2 workers...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 137 samples. (0 to 137)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 137 samples. (0 to 137)
  0%|          | 0/137 [00:00<?, ?it/s]

Rank 0 inferred the following `['str', 'str', 'str', 'no_header_tensor:1', 'tensor', 'no_header_tensor:1']` data format.

100%|██████████| 137/137 [00:00<00:00, 159.37it/s]

Worker 0 finished processing samples.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing samples.

Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/chart_only/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_2e0a5a6d-54c5-5666-abbc-c89b2572a579/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Task dataset built. Number of samples: 137
Train: 106
Val: 15
Test: 16
TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(24, 132, kernel_size=(5,), stride=(1,), groups=12)
      (bn_temporal): BatchNorm1d(132, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=192, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(204, 187, kernel_size=(5,), stride=(1,), dilation=(2,), groups=17)
      (bn_temporal): BatchNorm1d(187, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=252, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(264, 242, kernel_size=(5,), stride=(1,), dilation=(3,), groups=22)
      (bn_temporal): BatchNorm1d(242, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=312, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(324, 297, kernel_size=(5,), stride=(1,), dilation=(4,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(5,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(6,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(7,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(8,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=672, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

INFO:pyhealth.trainer:TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(24, 132, kernel_size=(5,), stride=(1,), groups=12)
      (bn_temporal): BatchNorm1d(132, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=192, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(204, 187, kernel_size=(5,), stride=(1,), dilation=(2,), groups=17)
      (bn_temporal): BatchNorm1d(187, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=252, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(264, 242, kernel_size=(5,), stride=(1,), dilation=(3,), groups=22)
      (bn_temporal): BatchNorm1d(242, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=312, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(324, 297, kernel_size=(5,), stride=(1,), dilation=(4,), groups=27)
      (bn_temporal): BatchNorm1d(297, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=372, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(384, 352, kernel_size=(5,), stride=(1,), dilation=(5,), groups=32)
      (bn_temporal): BatchNorm1d(352, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=432, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(444, 407, kernel_size=(5,), stride=(1,), dilation=(6,), groups=37)
      (bn_temporal): BatchNorm1d(407, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=492, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(504, 462, kernel_size=(5,), stride=(1,), dilation=(7,), groups=42)
      (bn_temporal): BatchNorm1d(462, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=552, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(564, 517, kernel_size=(5,), stride=(1,), dilation=(8,), groups=47)
      (bn_temporal): BatchNorm1d(517, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=612, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=672, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

Metrics: ['mae', 'mse']

INFO:pyhealth.trainer:Metrics: ['mae', 'mse']

Device: cpu

INFO:pyhealth.trainer:Device: cpu

INFO:pyhealth.trainer:

Training:

INFO:pyhealth.trainer:Training:

Batch size: 8

INFO:pyhealth.trainer:Batch size: 8

Optimizer: <class 'torch.optim.adam.Adam'>

INFO:pyhealth.trainer:Optimizer: <class 'torch.optim.adam.Adam'>

Optimizer params: {'lr': 0.00221}

INFO:pyhealth.trainer:Optimizer params: {'lr': 0.00221}

Weight decay: 0.0

INFO:pyhealth.trainer:Weight decay: 0.0

Max grad norm: None

INFO:pyhealth.trainer:Max grad norm: None

Val dataloader: None

INFO:pyhealth.trainer:Val dataloader: None

Monitor: mae

INFO:pyhealth.trainer:Monitor: mae

Monitor criterion: min

INFO:pyhealth.trainer:Monitor criterion: min

Epochs: 1

INFO:pyhealth.trainer:Epochs: 1

Patience: None

INFO:pyhealth.trainer:Patience: None

INFO:pyhealth.trainer:

Epoch 0 / 1:   0%|          | 0/14 [00:00<?, ?it/s]

--- Train epoch-0, step-14 ---

INFO:pyhealth.trainer:--- Train epoch-0, step-14 ---

loss: 1.5807

INFO:pyhealth.trainer:loss: 1.5807

Result: {'experiment': 'chart_only', 'mae': 2.571882724761963, 'mse': 16.85392189025879, 'kappa': 0.0, 'accuracy': 0.12015137180700095}

========== Running experiment: lab_plus_chart ==========
Lab features: 27
Chart features: 12
Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

INFO:pyhealth.datasets.mimic4:Using default EHR config: /content/PyHealth-TPC_LoS-AKV/pyhealth/datasets/configs/mimic4_ehr.yaml

Memory usage Before initializing mimic4_ehr: 4888.4 MB

INFO:pyhealth.datasets.mimic4:Memory usage Before initializing mimic4_ehr: 4888.4 MB

Duplicate table names in tables list. Removing duplicates.

WARNING:pyhealth.datasets.base_dataset:Duplicate table names in tables list. Removing duplicates.

Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

INFO:pyhealth.datasets.base_dataset:Initializing mimic4_ehr dataset from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2 (dev mode: False)

Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4

INFO:pyhealth.datasets.base_dataset:Using provided cache_dir: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4

Memory usage After initializing mimic4_ehr: 4888.4 MB

INFO:pyhealth.datasets.mimic4:Memory usage After initializing mimic4_ehr: 4888.4 MB

Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

INFO:pyhealth.datasets.base_dataset:Setting task RemainingLengthOfStayTPC_MIMIC4 for mimic4_ehr base dataset...

Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Task cache paths: task_df=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/task_df.ld, samples=/content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Applying task transformations on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying task transformations on data with 2 workers...

No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

INFO:pyhealth.datasets.base_dataset:No cached event dataframe found. Creating: /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet

Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: labevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/labevents.csv.gz

Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

INFO:pyhealth.datasets.base_dataset:Joining with table: /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/d_labitems.csv.gz

Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: chartevents from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/chartevents.csv.gz

Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: admissions from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/admissions.csv.gz

Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: patients from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/hosp/patients.csv.gz

Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

INFO:pyhealth.datasets.base_dataset:Scanning table: icustays from /content/drive/MyDrive/CS 598 DLH Project/datasets/mimic-iv-demo/2.2/icu/icustays.csv.gz

Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

INFO:pyhealth.datasets.base_dataset:Caching event dataframe to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/global_event_df.parquet...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 100 patients. (Polars threads: 2)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 100 patients. (Polars threads: 2)
  0%|          | 0/100 [00:00<?, ?it/s]

Rank 0 inferred the following `['bytes']` data format.

100%|██████████| 100/100 [00:02<00:00, 33.38it/s]

Worker 0 finished processing patients.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing patients.

Fitting processors on the dataset...

INFO:pyhealth.datasets.base_dataset:Fitting processors on the dataset...

Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

INFO:pyhealth.datasets.base_dataset:Processing samples and saving to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld...

Applying processors on data with 2 workers...

INFO:pyhealth.datasets.base_dataset:Applying processors on data with 2 workers...

Detected Jupyter notebook environment, setting num_workers to 1

INFO:pyhealth.datasets.base_dataset:Detected Jupyter notebook environment, setting num_workers to 1

Single worker mode, processing sequentially

INFO:pyhealth.datasets.base_dataset:Single worker mode, processing sequentially

Worker 0 started processing 137 samples. (0 to 137)

INFO:pyhealth.datasets.base_dataset:Worker 0 started processing 137 samples. (0 to 137)
  0%|          | 0/137 [00:00<?, ?it/s]

Rank 0 inferred the following `['str', 'str', 'str', 'no_header_tensor:1', 'tensor', 'no_header_tensor:1']` data format.

100%|██████████| 137/137 [00:01<00:00, 118.58it/s]

Worker 0 finished processing samples.

INFO:pyhealth.datasets.base_dataset:Worker 0 finished processing samples.

Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

INFO:pyhealth.datasets.base_dataset:Cached processed samples to /content/PyHealth-TPC_LoS-AKV/.ablation_cache/lab_plus_chart/f9b79777-8551-5286-8918-bfc795e1cfd4/tasks/RemainingLengthOfStayTPC_MIMIC4_0c03fd6d-815f-5a13-bf3d-0cc50ef4ba0a/samples_cdbbc602-34e2-5a41-8643-4c76b08829f6.ld

Task dataset built. Number of samples: 137
Train: 109
Val: 15
Test: 13
TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(78, 429, kernel_size=(5,), stride=(1,), groups=39)
      (bn_temporal): BatchNorm1d(429, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=516, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(528, 484, kernel_size=(5,), stride=(1,), dilation=(2,), groups=44)
      (bn_temporal): BatchNorm1d(484, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=576, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(588, 539, kernel_size=(5,), stride=(1,), dilation=(3,), groups=49)
      (bn_temporal): BatchNorm1d(539, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=636, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(648, 594, kernel_size=(5,), stride=(1,), dilation=(4,), groups=54)
      (bn_temporal): BatchNorm1d(594, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=696, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(708, 649, kernel_size=(5,), stride=(1,), dilation=(5,), groups=59)
      (bn_temporal): BatchNorm1d(649, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=756, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(768, 704, kernel_size=(5,), stride=(1,), dilation=(6,), groups=64)
      (bn_temporal): BatchNorm1d(704, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=816, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(828, 759, kernel_size=(5,), stride=(1,), dilation=(7,), groups=69)
      (bn_temporal): BatchNorm1d(759, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=876, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(888, 814, kernel_size=(5,), stride=(1,), dilation=(8,), groups=74)
      (bn_temporal): BatchNorm1d(814, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=936, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=996, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

INFO:pyhealth.trainer:TPC(
  (blocks): ModuleList(
    (0): TPCBlock(
      (temporal_conv): Conv1d(78, 429, kernel_size=(5,), stride=(1,), groups=39)
      (bn_temporal): BatchNorm1d(429, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=516, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (1): TPCBlock(
      (temporal_conv): Conv1d(528, 484, kernel_size=(5,), stride=(1,), dilation=(2,), groups=44)
      (bn_temporal): BatchNorm1d(484, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=576, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (2): TPCBlock(
      (temporal_conv): Conv1d(588, 539, kernel_size=(5,), stride=(1,), dilation=(3,), groups=49)
      (bn_temporal): BatchNorm1d(539, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=636, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (3): TPCBlock(
      (temporal_conv): Conv1d(648, 594, kernel_size=(5,), stride=(1,), dilation=(4,), groups=54)
      (bn_temporal): BatchNorm1d(594, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=696, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (4): TPCBlock(
      (temporal_conv): Conv1d(708, 649, kernel_size=(5,), stride=(1,), dilation=(5,), groups=59)
      (bn_temporal): BatchNorm1d(649, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=756, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (5): TPCBlock(
      (temporal_conv): Conv1d(768, 704, kernel_size=(5,), stride=(1,), dilation=(6,), groups=64)
      (bn_temporal): BatchNorm1d(704, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=816, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (6): TPCBlock(
      (temporal_conv): Conv1d(828, 759, kernel_size=(5,), stride=(1,), dilation=(7,), groups=69)
      (bn_temporal): BatchNorm1d(759, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=876, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
    (7): TPCBlock(
      (temporal_conv): Conv1d(888, 814, kernel_size=(5,), stride=(1,), dilation=(8,), groups=74)
      (bn_temporal): BatchNorm1d(814, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_temporal): Dropout(p=0.05, inplace=False)
      (pointwise): Linear(in_features=936, out_features=5, bias=True)
      (bn_pointwise): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (dropout_main): Dropout(p=0.0, inplace=False)
      (relu): ReLU()
    )
  )
  (head_fc1): Linear(in_features=996, out_features=36, bias=True)
  (head_relu): ReLU()
  (head_fc2): Linear(in_features=36, out_features=1, bias=True)
  (hardtanh): Hardtanh(min_val=0.020833333333333332, max_val=100.0)
)

Metrics: ['mae', 'mse']

INFO:pyhealth.trainer:Metrics: ['mae', 'mse']

Device: cpu

INFO:pyhealth.trainer:Device: cpu

INFO:pyhealth.trainer:

Training:

INFO:pyhealth.trainer:Training:

Batch size: 8

INFO:pyhealth.trainer:Batch size: 8

Optimizer: <class 'torch.optim.adam.Adam'>

INFO:pyhealth.trainer:Optimizer: <class 'torch.optim.adam.Adam'>

Optimizer params: {'lr': 0.00221}

INFO:pyhealth.trainer:Optimizer params: {'lr': 0.00221}

Weight decay: 0.0

INFO:pyhealth.trainer:Weight decay: 0.0

Max grad norm: None

INFO:pyhealth.trainer:Max grad norm: None

Val dataloader: None

INFO:pyhealth.trainer:Val dataloader: None

Monitor: mae

INFO:pyhealth.trainer:Monitor: mae

Monitor criterion: min

INFO:pyhealth.trainer:Monitor criterion: min

Epochs: 1

INFO:pyhealth.trainer:Epochs: 1

Patience: None

INFO:pyhealth.trainer:Patience: None

INFO:pyhealth.trainer:

Epoch 0 / 1:   0%|          | 0/14 [00:00<?, ?it/s]

--- Train epoch-0, step-14 ---

INFO:pyhealth.trainer:--- Train epoch-0, step-14 ---

loss: 1.6719

INFO:pyhealth.trainer:loss: 1.6719

Result: {'experiment': 'lab_plus_chart', 'mae': 0.9013709425926208, 'mse': 2.091479539871216, 'kappa': -0.012257715015012272, 'accuracy': 0.30402010050251255}

In [ ]:
results_df = pd.DataFrame(all_results)
results_df

       experiment       mae        mse     kappa  accuracy
0        lab_only  1.850556  10.661468  0.006732  0.189166
1      chart_only  2.571883  16.853922  0.000000  0.120151
2  lab_plus_chart  0.901371   2.091480 -0.012258  0.304020

In [ ]:
results_df.sort_values("mae")

       experiment       mae        mse     kappa  accuracy
2  lab_plus_chart  0.901371   2.091480 -0.012258  0.304020
0        lab_only  1.850556  10.661468  0.006732  0.189166
1      chart_only  2.571883  16.853922  0.000000  0.120151

In [ ]:
save_path = "/content/drive/MyDrive/CS 598 DLH Project/ablation_results.csv"
results_df.to_csv(save_path, index=False)
print("Saved to:", save_path)

Saved to: /content/drive/MyDrive/CS 598 DLH Project/ablation_results.csv

In [ ]:
best_row = results_df.sort_values("mae").iloc[0]

print("Best configuration:")
print(best_row)

print("\nInterpretation template:")
print(
    f"The best-performing ablation setting was {best_row['experiment']} "
    f"with MAE={best_row['mae']:.4f}, MSE={best_row['mse']:.4f}, "
    f"Kappa={best_row['kappa']:.4f}, Accuracy={best_row['accuracy']:.4f}."
)

Best configuration:
experiment    lab_plus_chart
mae                 0.901371
mse                  2.09148
kappa              -0.012258
accuracy             0.30402
Name: 2, dtype: object

Interpretation template:
The best-performing ablation setting was lab_plus_chart with MAE=0.9014, MSE=2.0915, Kappa=-0.0123, Accuracy=0.3040.